name: random
description: A random connect project.

publish_to: 'none'

version: 0.1.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  share_plus: ^7.0.2
  image_picker: ^1.0.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.0
  store_redirect: ^2.0.1
  webview_flutter: ^4.2.4
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.2
  firebase_storage: ^11.2.2
  connectivity_plus: ^4.0.2
  shared_preferences: ^2.1.2
  emoji_picker_flutter: ^1.6.1
  cached_network_image: ^3.2.3
  curved_navigation_bar: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
