// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // ignore: public_member_api_docs
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ignore: public_member_api_docs
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqesrUKz6db1GB8P-XDPmdZxZstSfJE4I',
    appId: '1:17134732223:web:8d3729ff344bcd3dd5170a',
    messagingSenderId: '17134732223',
    projectId: 'random-49876',
    authDomain: 'random-49876.firebaseapp.com',
    databaseURL:
        'https://random-49876-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'random-49876.appspot.com',
    measurementId: 'G-5DHXJBX7D1',
  );

  // ignore: public_member_api_docs
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcgrFQo5lUmJ-A-MdwS1H1nnN49sjTqBA',
    appId: '1:17134732223:android:9d888920f6b55a6ad5170a',
    messagingSenderId: '17134732223',
    projectId: 'random-49876',
    databaseURL:
        'https://random-49876-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'random-49876.appspot.com',
  );

  // ignore: public_member_api_docs
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNZl7nKUcaH-THoo3HT54OilASFheCKPY',
    appId: '1:17134732223:ios:a27ec3b9bee73476d5170a',
    messagingSenderId: '17134732223',
    projectId: 'random-49876',
    databaseURL:
        'https://random-49876-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'random-49876.appspot.com',
    iosBundleId: 'com.example.random',
  );
}
